In [5]:
import numpy as np
np.__version__

'1.16.5'

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
array = np.array([[1,2,3],[4,5,6]])

In [11]:
array[0]

array([1, 2, 3])

In [12]:
array[0, :2]

array([1, 2])

In [13]:
array[0, 2]

3

In [14]:
array.ndim

2

In [15]:
array.shape

(2, 3)

In [16]:
array.dtype

dtype('int32')

In [17]:
array.sum()

21

In [18]:
array.min()

1

In [19]:
array.max()

6

In [20]:
array.mean()

3.5

In [21]:
array.std()

1.707825127659933

In [22]:
array.std(ddof = 1)

1.8708286933869707

In [23]:
nums = np.array([1, 2, 2, 3])

In [24]:
nums

array([1, 2, 2, 3])

In [25]:
set(nums)

{1, 2, 3}

In [26]:
np.unique(nums)

array([1, 2, 3])

In [27]:
len(nums)

4

In [28]:
np.arange(3, 8, 2)

array([3, 5, 7])

In [29]:
np.where(nums == 2, 1, 0)

array([0, 1, 1, 0])

In [30]:
import pandas as pd

In [31]:
pd.__version__

'0.25.1'

In [32]:
ser = pd.Series([1, 2, 3])

In [33]:
ser

0    1
1    2
2    3
dtype: int64

In [34]:
ser.values

array([1, 2, 3], dtype=int64)

In [35]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [36]:
pd.Series([1,2,3], index=["a","b","c"])

a    1
b    2
c    3
dtype: int64

In [37]:
ser  = pd.Series([1, 2, 2, 3, 4])

In [38]:
ser.sum()

12

In [39]:
ser.min()

1

In [40]:
ser.max()

4

In [41]:
ser.mean()

2.4

In [42]:
ser.std()

1.140175425099138

In [43]:
ser.skew()

0.40479600891093703

In [44]:
ser.kurt()

-0.17751479289940786

In [45]:
ser.unique()

array([1, 2, 3, 4], dtype=int64)

In [46]:
ser.kurtosis()

-0.17751479289940786

In [47]:
ser.idxmax()

4

In [48]:
ser.isin([1, 2])

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [49]:
ser[ser.isin([1, 2])]

0    1
1    2
2    2
dtype: int64

In [50]:
ser = pd.Series([1,2,3,3,4])

In [51]:
ser[0]

1

In [52]:
ser[[1,3]]

1    2
3    3
dtype: int64

In [53]:
ser[:3]

0    1
1    2
2    3
dtype: int64

In [54]:
ser[:-1]

0    1
1    2
2    3
3    3
dtype: int64

In [55]:
pd.DataFrame([[1,2,3],[4,5,6]])

0  1  2
0  1  2  3
1  4  5  6

In [56]:
pd.DataFrame({"aa":[1,2,3], "bb":[4,5,6]})

aa  bb
0   1   4
1   2   5
2   3   6

In [57]:
pd.DataFrame([[1,2],[3,4],[5,6]], columns=["xx","yy"])

xx  yy
0   1   2
1   3   4
2   5   6

In [58]:
pd.DataFrame(np.arange(4).reshape((2,2)), columns=["a","b"])

a  b
0  0  1
1  2  3

In [59]:
df = pd.DataFrame({"aa":[1,2,3],"bb":[4,5,6]})

In [60]:
df

aa  bb
0   1   4
1   2   5
2   3   6

In [61]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [62]:
df["aa"] #이게 오류를 방지

0    1
1    2
2    3
Name: aa, dtype: int64

In [63]:
df["aa"][:2]

0    1
1    2
Name: aa, dtype: int64

In [64]:
df.iloc[:2]

aa  bb
0   1   4
1   2   5

In [65]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [66]:
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [67]:
df.iloc[:2, :]

aa  bb
0   1   4
1   2   5

In [70]:
df.iloc[:2, 0]

0    1
1    2
Name: aa, dtype: int64

In [72]:
pd.crosstab(df["aa"], df["bb"])

bb  4  5  6
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [73]:
df

aa  bb
0   1   4
1   2   5
2   3   6

In [74]:
df.groupby("aa")["bb"].sum()

aa
1    4
2    5
3    6
Name: bb, dtype: int64

In [78]:
df2 = pd.DataFrame({"v1": [1,1,2,2,3,3,3], "v2": [23,45,65,78,23,12,512]})

In [79]:
df2.groupby("v1")["v2"].mean()

v1
1     34.000000
2     71.500000
3    182.333333
Name: v2, dtype: float64